on:
  schedule:
    - cron: '0 * * * *'

jobs:
  update_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install packages
        run: pip install -r ${{ github.workspace }}/requirements.txt

      - name: Generate tables
        run: python ${{ github.workspace }}/gen.py

      - name: Detect changes
        id: detect_changes
        run: |
          if git diff --quiet; then
            echo "::set-output name=updated::false"
          else
            echo "::set-output name=updated::true"
          fi

      - name: Commit
        if: ${{ steps.detect_changes.outputs.updated == 'true' }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Update from CDC data'
          git push origin master
